<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\AuditLog;
use App\Models\RecurringOrder;
use Illuminate\Http\Request;

class RecurringOrderController extends Controller
{
    public function index(Request $request)
    {
        $query = RecurringOrder::with(['customer.user', 'customer.company', 'template', 'deliveryAddress']);

        if ($request->filled('search')) {
            $search = $request->search;
            $query->whereHas('customer.user', fn($q) => $q->where('name', 'like', "%{$search}%")->orWhere('email', 'like', "%{$search}%"));
        }

        if ($request->filled('status')) {
            $query->where('is_active', $request->status === 'active');
        }

        if ($request->filled('frequency')) {
            $query->where('frequency', $request->frequency);
        }

        $recurringOrders = $query->orderBy('next_run_date', 'asc')->paginate(30);

        // Stats
        $totalActive = RecurringOrder::where('is_active', true)->count();
        $totalPaused = RecurringOrder::where('is_active', false)->count();
        $dueThisWeek = RecurringOrder::where('is_active', true)
            ->whereBetween('next_run_date', [now(), now()->addWeek()])
            ->count();
        $frequencies = RecurringOrder::select('frequency')
            ->selectRaw('count(*) as count')
            ->groupBy('frequency')
            ->pluck('count', 'frequency');

        return view('admin.recurring-orders.index', compact(
            'recurringOrders', 'totalActive', 'totalPaused', 'dueThisWeek', 'frequencies'
        ));
    }

    public function show(RecurringOrder $recurringOrder)
    {
        $recurringOrder->load(['customer.user', 'customer.company', 'template', 'deliveryAddress']);

        // Find orders generated by this recurring order (match customer + notes pattern)
        $generatedOrders = $recurringOrder->customer->orders()
            ->where('notes', 'like', '%recurring%')
            ->orderBy('created_at', 'desc')
            ->take(20)
            ->get();

        return view('admin.recurring-orders.show', compact('recurringOrder', 'generatedOrders'));
    }

    public function pause(RecurringOrder $recurringOrder)
    {
        $recurringOrder->update(['is_active' => false]);

        AuditLog::log('paused_recurring_order', 'RecurringOrder', $recurringOrder->id);

        return back()->with('success', 'Recurring order paused.');
    }

    public function resume(RecurringOrder $recurringOrder)
    {
        $recurringOrder->update([
            'is_active' => true,
            'next_run_date' => $recurringOrder->next_run_date < now()
                ? now()->addDay()
                : $recurringOrder->next_run_date,
        ]);

        AuditLog::log('resumed_recurring_order', 'RecurringOrder', $recurringOrder->id);

        return back()->with('success', 'Recurring order resumed. Next run: ' . $recurringOrder->fresh()->next_run_date->format('d M Y'));
    }

    public function updateFrequency(Request $request, RecurringOrder $recurringOrder)
    {
        $request->validate([
            'frequency' => 'required|in:weekly,biweekly,monthly',
            'next_run_date' => 'required|date|after:today',
        ]);

        $old = $recurringOrder->frequency;
        $recurringOrder->update([
            'frequency' => $request->frequency,
            'next_run_date' => $request->next_run_date,
        ]);

        AuditLog::log('updated_recurring_order', 'RecurringOrder', $recurringOrder->id, [
            'old_frequency' => $old,
            'new_frequency' => $request->frequency,
            'next_run_date' => $request->next_run_date,
        ]);

        return back()->with('success', 'Recurring order updated.');
    }

    public function export(Request $request)
    {
        $query = RecurringOrder::with(['customer.user', 'template', 'deliveryAddress']);

        if ($request->filled('status')) {
            $query->where('is_active', $request->status === 'active');
        }

        $filename = 'recurring-orders-' . now()->format('Y-m-d') . '.csv';
        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => "attachment; filename=\"{$filename}\"",
        ];

        return response()->stream(function () use ($query) {
            $handle = fopen('php://output', 'w');
            fputcsv($handle, ['Customer', 'Email', 'Template', 'Frequency', 'Next Run', 'Last Run', 'Status', 'Items', 'Delivery Address']);

            $query->chunk(200, function ($orders) use ($handle) {
                foreach ($orders as $order) {
                    $itemCount = is_array($order->items) ? count($order->items) : 0;
                    fputcsv($handle, [
                        $order->customer?->user?->name ?? '-',
                        $order->customer?->user?->email ?? '-',
                        $order->template?->name ?? '-',
                        ucfirst($order->frequency),
                        $order->next_run_date?->format('Y-m-d') ?? '-',
                        $order->last_run_date?->format('Y-m-d') ?? 'Never',
                        $order->is_active ? 'Active' : 'Paused',
                        $itemCount . ' item(s)',
                        $order->deliveryAddress?->line_1 ?? '-',
                    ]);
                }
            });

            fclose($handle);
        }, 200, $headers);
    }
}
